project:
  type: website

website:
  title: "IUCN GET map documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Functional groups"
        href: efg-info.qmd
      - text: "Map information"
        href: map-info.qmd
    right:
      - text: "About"
        menu:
          - about.qmd
          - how2/this-site.qmd
          - how2/download-with-R.qmd
          - how2/additional-map-details.qmd
  margin-header: |
    <center>![Global Ecosystem Typology](/assets/logo_RLE.png)</center>
  page-footer:
    left: "Created by: JR Ferrer-Paris"
    right:
      - icon: github
        href: https://github.com/jrfep
format:
  html:
    theme: mint
    css: styles.css
    highlight-style: solarized
    toc: true

execute:
  freeze: true  # never re-render during project render


