project:
  type: website

website:
  title: "IUCN GET map documentation"
  navbar:
    left:
      - text: "Typology"
        menu:
        - href: index.qmd
          text: Home
        - href: summary.qmd
          text: Summary
        - href: development.qmd
          text: Development
        - href: feedback.qmd
          text: Feedback
        - href: glossary.md
          text: Glossary
      - text: "Functional groups"
        menu:
          - href: profile-structure.qmd
            text: "Profile structure"
          - href: efg-info.qmd
            text: "Overview"
      - text: "Map information"
        menu:
          - text: "Map evaluation"
            href: map-evaluation.qmd
          - text: "Current maps"
            href: map-info.qmd
          - text: "Version history"
            href: map-version-history.qmd
          - text: "Map updates"
            href: map-updates.qmd
    right:
      - text: "How to..."
        menu:
          - how2/download-with-R.qmd
          - how2/additional-map-details.qmd
      - text: "About"
        menu:
          - about.qmd
          - how2/this-site.qmd
  margin-header: |
    <center>![Global Ecosystem Typology](/assets/logo_RLE.png)</center>
  page-footer:
    left: "This site is maintained by: JR Ferrer-Paris"
    right:
      - text: "Repository available at:"
      - icon: github
        href: https://github.com/red-list-ecosystem/typology-map-info
  comments:
    utterances:
      repo: red-list-ecosystem/typology-map-info
format:
  html:
    theme: mint
    css: styles.css
    highlight-style: solarized
    toc: true

execute:
  freeze: auto  # never re-render during project render


