project:
  type: website

website:
  title: "IUCN GET map documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - how2/this-site.qmd
      - how2/download-with-R.qmd
      - text: "Map information"
        href: map-info.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: solarized
    toc: true



