---
title: "Map version history"
execute: 
  echo: false
  warning: false
  message: false
---

## General notes on maps

The maps in each profile show areas of the world containing major or minor occurrences of the ecosystem functional group. Minor occurrences are areas where an EFG is scattered in patches within matrices of others or where they occur in substantial areas but only within a segment of a larger region.

The maps were designed to be indicative of global distribution patterns and are not intended to represent fine-scale patterns. Given bounds of resolution and accuracy of source data, the maps should be used to query which EFG are likely to occur within areas, rather than which occur at particular point locations.

## Version history

Please follow the links in the following table to review the version history for a particular functional group. You can filter by biome name or functional group name.

```{r}
library(readxl)
library(dplyr)
library(readr)
library(DT)
library(stringr)

here::i_am("map-version-history.qmd")

out_folder <- here::here("gisdata", "profiles")
dest_file <- here::here(out_folder,  "biome-names.csv")
biome_names <- read_csv(dest_file, show_col_types = FALSE) |>
    rename("biome code" = "biome_code" , "biome name" = "name") 

dest_file <- here::here(out_folder,  "IUCN-GET-profiles-exported.xlsx")
profile_info <- read_excel(dest_file, sheet = 2) |> 
    left_join(biome_names, by = "biome code")

altmap_table <- profile_info |>
    transmute(Biome = `biome name`, `Ecosystem functional group` = name,
    `Links` = sprintf("<a href='map-info/%1$s_valid.html'>Current version</a> / <a href='altmap-info/%1$s_history.html'>Version history</a>", str_replace(`code`,"\\.", "_")))
DT::datatable(altmap_table, rownames = FALSE, escape = FALSE, filter = 'top',
    options = list(dom = 'tpl', pageLength = 25,
        columnDefs = list(list(targets = 2, searchable = FALSE))
    ))
```