---
layout: default
title: Ecosystem Functional Groups
---

<p>Expert working groups for each realm delineated candidate ecosystem functional groups (Level 3) through a [development and review process](development.qmd). They identified gradients in key assembly filters for each biome and identified major ecosystem and species traits that vary along them. In terrestrial environments, key assembly gradients include water deficit, seasonality, temperature, nutrient deficiency, fire activity and herbivory. In subterranean environments, substrate structure is a major factor. In freshwater environments, gradients in flow continuity and velocity, water body size, seasonal freezing and salinity are key assembly filters. In marine environments, depth gradients in light, vertical and horizontal movement of nutrients and substrate stability and particle size are major assembly filters.

Experts delineated candidate functional groups by identifying distinctive sets of traits associated with particular segments of the assembly filter space defined by the gradients.

For each candidate ecosystem functional group, we represented the key drivers and traits in simplified conceptual models derived from the generic assembly model (Keith et al. in review) as a basis for review and description. We adjusted and augmented descriptions based on published reviews (see cited references in the descriptive profiles below) and in consultation with broader networks of specialists (e.g. through <a href="https://www.iucn.org/commissions/commission-ecosystem-management/about">IUCN’s Commission on Ecosystem Management biome specialist groups</a>.

Finally, we prepared indicative global distribution maps from available spatial data. In some cases, high-resolution published maps were available (e.g. Murray et al. 2019). In other cases, we prepared coarse resolution maps using environmental proxies (e.g. Harris et al. 2004) or by identifying ecoregions documented as containing major or minor occurrences of ecosystem types referrable to respective functional groups (Spalding et al. 2007; Abell et al. 2008; Dinerstein et al. 2017). Occurrence information was gleaned from descriptions of ecoregions, references cited in the descriptive profiles for respective functional groups and personal observations of the authors.

Check the [list of Ecosystem Functional Groups](efg-info.qmd) with links to their profiles.

## Descriptive profiles for Ecosystem Functional Groups

The descriptive profiles provide brief summaries of key ecological traits and processes for each functional group of ecosystems to enable any ecosystem type to be assigned to a group. The descriptions aim to identify explicit features that distinguish different functional groups to inform diagnosis and identification. However, there may be inherent uncertainties in assigning ecosystem types to unique functional groups because ecological classifications, in general, simplify complex variation in nature by segmenting and categorising fundamentally continuous gradients in multiple features. Thus, any given ecosystem type of interest may possess a suite of features that are typical of different functional groups.  Users should apply weight of evidence to identify the most likely functional group, including distributional information, and report the nature of uncertainties.

### Nomenclature

Names of functional groups are vernacular, adopting names and descriptors frequently applied in the literature and reflecting key functional features. A vernacular, rather than systematic approach to nomenclature is intended to exploit terms (e.g. rainforest, lake, reef) that are familiar to a wide range of users, recognising regional variations and conventions in terminology.

### Text descriptions

The text describes key ecological traits diagnosed from literature and expert knowledge that characterise each functional group and help distinguish it from other groups. The descriptions include ecosystem-level traits (e.g. productivity, energy sources, trophic structure, physical structure, bottom-up and top-down organisational processes, etc.) as well as species-level traits that are commonly represented among the component biota of ecosystem types within the group (e.g. life forms, life-history traits, specialised organs, characteristic behaviours and mobility, etc.). See Tables S4.1 and S4.2 for explanation of terms. Where possible, variability in traits is noted. The following table provides a brief glossary of selected terms used in the profiles (see Pérez-Harguindeguy et al. 2013 for further details on plant traits).

<!--//
# Exemplary photograph

Each profile is illustrated with a photograph that shows some of the ecological features mentioned in the text. Although representative examples were chosen for illustration, they may not represent the range of variability in features expressed within each functional group, some of which have extensive global distributions.
//-->

A workbook with profile content for Ecosystem Functional Groups of the IUCN Global Ecosystem Typology (Level 3 units) is available in an [OSF repository](https://osf.io/4dcea).

### Major ecosystem drivers

The text identifies key ecological drivers that shape the ecological character of ecosystem types within a functional group. These are primarily abiotic features and processes, including disturbance regimes that directly or indirectly influence resource availability. Human influence is only addressed in anthropogenic ecosystem functional groups, even though it profoundly affects most ecosystems on earth. These effects vary greatly in type, intensity and spatially in a manner that reflects social, cultural and economic norms and opportunities, technology and access, etc. as well as ecosystem characteristics. Specific influences of anthropogenic processes ecosystem state and will therefore be addressed in IUCN Red List assessments.

### Diagrammatic assembly models

For each Ecosystem Functional Group, the generic ecosystem assembly model <!--//presented in the main text (Fig. 1) //--> has been adapted to illustrate key ecological traits and assembly filters (drivers that shape ecosystem traits). Only the major features are shown and anthropogenic processes are only shown for anthropogenic functional groups (see below). Ecological traits are listed in green circles at centre, while drivers are identified in peripheral boxes (pale blue - resources, dark blue – ambient environmental factors that influence resource availability or uptake, red – environmental disturbance regimes, orange – biotic interactions, black – human activities). Connecting arrows show influences of, and interactions among drivers (only major connections shown, feedbacks generally not shown).

### Indicative distribution maps

Maps are indicative of global distribution patterns are not intended to represent fine-scale patterns. The maps show areas of the world containing major (coloured red) or minor occurrences (coloured yellow) of each ecosystem functional group. Minor occurrences are areas where an ecosystem functional group is scattered in patches within matrices of other ecosystem functional groups or where they occur in substantial areas, but only within a segment of a larger region. Small but important occurrences are identified with an indicative black ellipse. Most maps were prepared using a coarse-scale template (e.g. ecoregions of Spalding et al. 2007; Abell et al. 2008; Dinerstein et al. 2017), but some were compiled from higher resolution spatial data where available (see details below). Higher resolution mapping is planned in future publications.

We emphasise that spatial representation of Ecosystem Functional Groups does not follow higher-order groupings described in respective ecoregion classifications (provinces of Spalding 2007; major habitat types of Abell et al. 2008; biomes of Olsen et al. 2001 and Dinerstein et al. 2017). Consequently, when Ecosystem Functional Groups are aggregated into functional biomes (Level 2 of the Global Ecosystem Typology), spatial patterns may differ from those of biogeogreaphic biomes as mapped by Olsen et al (2001) and Dinerstein et al. (2017). Differences reflect the distinctions between functional and biogeographic interpretations of the term, “biome” (Mucina 2018).

Indicative maps are available in a data repository:
Keith, David A., Ferrer-Paris, Jose R., Nicholson, Emily, & Kingsford, Richard T. (eds.) (2020). Indicative distribution maps for Ecosystem Functional Groups - Level 3 of IUCN Global Ecosystem Typology (Version 2.1.1) [Data set]. Zenodo. DOI: [10.5281/zenodo.3546513](10.5281/zenodo.3546513)

### References

Key references are listed as sources of further information for each functional group. Preference has been given to recent global reviews, and where these are not available, regional reviews or publications addressing key ecological processes that characterise the system.
