---
execute: 
 eval: false
---
# We built this site...

on [Rock and Roll](https://www.gq.com/story/oral-history-we-built-this-city-worst-song-of-all-time){target='external'}!... and [Quarto](https://quarto.org){target='external'}, [RStudio](https://posit.co/download/rstudio-desktop/){target='external'}, [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/){target='external'}, [git](https://git-scm.com){target='external'}, [zsh](https://www.zsh.org){target='external'}/[bash](https://www.gnu.org/software/bash/Rstudio){target='external'} lots of packages and modules, and immoderate amounts of coffee.

Here are the basics to get started. 
Once this site is up and running, you can follow the git log history to see all the additional steps  went into creating this amazing and wonderful website.

## Create quarto website project

```{.bash filename="Terminal"}
cd $PROJECTDIR/
quarto create project website typology-map-info
```

## git it!

```{.bash filename="Terminal"}
cd $PROJECTDIR/typology-map-info
git init
```

## Activate Jupyter Lab

For editing jupyter notebooks activate a python environment with jupyter modules installed. For example, using `venv`:

```{.bash filename="Terminal"}
source ~/venv/jptr/bin/activate
```
## Enable commenting

We enable [Utterances](https://utteranc.es) commenting using the `utterances` option. 

First install the [utterances app]() in the repo.

For this we specify the GitHub repo for storing comments:

```{.yaml}
comments:
  utterances:
    repo: red-list-ecosystem/typology-map-info
```

## quarto publish command

First create the gh-pages branch:

```{.bash filename="Terminal"}
git checkout --orphan gh-pages
git reset --hard # make sure all changes are committed before running this!
git commit --allow-empty -m "Initialising gh-pages branch"
git push origin gh-pages
```

Then ensure that the **Source** branch of the repository is `gh-pages` and that the site directory is set to the repository root (`/`). Check **Settings : Pages** in our repository.

Now we can do:

```{.bash filename="Terminal"}
git checkout main
quarto publish gh-pages
```

And this site is up and running!