---
execute: 
 eval: false
---

# Indicative map data

Data is available from Zenodo repository:

## Data download with R

Use library `here` to define relative paths
```{r}
here::i_am("how2/zenodo-download.qmd")
```

```{r}
library(zen4R)
library(parallel)

# This will resolve to the latest version
doi = "10.5281/zenodo.3546513"

out_folder <- here::here("gisdata", "indicative-maps","latest")

if (!dir.exists(out_folder))
    dir.create(out_folder, recursive = TRUE)

## download to output folder
## `options(timeout=500)` will get overwritten by argument
download_zenodo(doi=doi, path = (out_folder), timeout = 500)

## for some reason the parallel download does not work with the `path` argument:
#download_zenodo(doi=doi, 
#    parallel = TRUE, 
#    parallel_handler = parLapply, 
#    cl = makeCluster(2))
```

```{r}
workdir <- tempdir()
rast_tar <- here::here(out_folder, "all-maps-raster-geotiff.tar.bz2")
rast_list <- untar(rast_tar, list = TRUE)
untar(rast_tar, files = grep("^T1.1",rast_list, value = T), exdir = workdir)

```