```{r setup}
#| warning: false
#| message: false
library(xml2)
library(terra)
library(magick)
library(RPostgreSQL)
library(dplyr)

efg_code <- params$efgcode
efg_code_ <- gsub("\\.","_",efg_code)
here::i_am(sprintf("map-info/%s_valid.qmd", efg_code_))
out_folder <- here::here("gisdata", "indicative-maps-bundle","latest")
```

```{r}
xpath_map_efg <- sprintf("//Map[@efg_code='%s']", efg_code)
map_details_file <- paste(out_folder, "map-details.xml", sep = "/")
# file.exists(map_details_file)
map_details <- read_xml(map_details_file)
map_info <- map_details |> xml_find_first(xpath_map_efg)
map_attrs <- map_info |> xml_attrs()
efg_name <- map_info |> xml_find_first("Functional_group") |> xml_text()
ds_doi <- map_info |> xml_find_first("Dataset-doi") |> xml_text()
downloaded_copy <- here::here("gisdata", "indicative-maps", ds_doi)
efg_details <- read_xml(dir(downloaded_copy, "xml", full.names = TRUE))
```


```{r}
#| output: asis
markdown_text <- sprintf("The current valid map is identified by **Map code and version**: %1$s %2$s.",
        map_attrs["map_code"],
        map_attrs["map_version"]
)

cat(markdown_text)
```


```{r}
#| output: asis
markdown_text <- sprintf("> %s.",
    map_info |> xml_find_first("Description") |> xml_text()
)
cat(markdown_text)
```

```{r}
#| message: false
#| results: hide
drv <- dbDriver("PostgreSQL") ## remember to update .pgpass file

con <- dbConnect(drv, 
                 dbname = Sys.getenv("DBNAME"),
                 host = Sys.getenv("DBHOST"),
                 port = Sys.getenv("DBPORT"),
                 user = Sys.getenv("DBUSER"))

qry <- sprintf("select map_file, file_description, file_comments, map_script from map_files where map_code like '%s' and map_version = '%s';", map_attrs["map_code"], map_attrs["map_version"])

map_files <- dbGetQuery(con,qry) 

dbDisconnect(con)
```


You can download and use this file from the following sources:

```{r}
#| results: asis
mdtexts <- map_files |>
    filter(grepl("^http", map_file)) |>
    mutate(mdtext = sprintf("- %s ([%s](%s))\n",file_description, file_comments, map_file)) |>
    pull(mdtext)

cat(mdtexts)
```