---
title: "T1.1 Tropical/Subtropical lowland rainforests"
subtitle: "T1 Tropical-subtropical forests"
date: 2024 May 6
categories:
 - T1
format:
 html: 
  code-tools:
   source: true
execute:
   echo: false
---

```{r setup}
#| warning: false
#| message: false
library(xml2)
library(terra)
library(magick)

here::i_am("efg-info/T1_1.qmd")
out_folder <- here::here("gisdata", "indicative-maps-bundle","latest")

map_details_file <- paste(out_folder, "map-details.xml", sep = "/")
# file.exists(map_details_file)
map_details <- read_xml(map_details_file)
map_info <- map_details |> xml_find_first("//Map[@efg_code='T1.1']")
map_attrs <- map_info |> xml_attrs()
ds_doi <- map_info |> xml_find_first("Dataset-doi") |> xml_text()
downloaded_copy <- here::here("gisdata", "indicative-maps", ds_doi)
efg_details <- read_xml(dir(downloaded_copy,"xml", full.names = TRUE))
```

```{r}
#| output: asis
efg_details |> xml_find_first("//Short-description") |> xml_text() |> cat()
```

Read more at: <https://global-ecosystems.org/explore/groups/T1.1>{target="webapp"}

```{r}
#| output: asis

markdown_text <- sprintf("## Map description\n\n ***%1$s***\n\n%2$s.\n\n **Map code and version**: %3$s %4$s. **Available at** DOI:[%5$s](https://doi.org/%5$s)",
    map_info |> xml_find_first("Functional_group") |> xml_text(),
    map_info |> xml_find_first("Description") |> xml_text(),
        map_attrs["map_code"],
        map_attrs["map_version"],
       ds_doi 
)

cat(markdown_text)
```

```{r}
thmbmap <- dir(downloaded_copy,"png", full.names = TRUE)
raw_img <- image_read(thmbmap)
image_ggplot(raw_img)
```

Read more details about this map [here](/map-info/T1_1_valid.qmd).

Read more details about older versions of this map [here](/map-info/T1_1_history.qmd).